---
- hosts: digitalocean

  tasks:   
    - name: pwd
      local_action: command pwd
    - name: spin up DO droplet
      local_action:
        module: digital_ocean 
             state=present
             command=droplet
             name=droplet-ansible
             api_token=xxxxx
             ssh_key_ids=xxxx
             size_id=s-1vcpu-1gb
             region_id=nyc1
             image_id=ubuntu-18-04-x64
             wait_timeout=500
      register: my_droplet
    - name: print info about my_droplet
      local_action:
        module:  debug
            msg="ID is {{ my_droplet.droplet.id }} IP is {{ my_droplet.droplet.ip_address }}"
          
    - name: Add new droplet to host group
      local_action: add_host hostname={{ my_droplet.droplet.ip_address }} groupname=launched ansible_ssh_user=root
    - name: Wait for SSH to come up
      local_action: wait_for host={{ my_droplet.droplet.ip_address }} port=22 delay=60 timeout=320 state=started

- hosts: launched
  gather_facts: False  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - include: php.yml
  handlers:
  - name: restart php-fpm
    service: name=php7.2-fpm state=restarted
  - name: restart nginx
    service: name=nginx state=restarted
